### ISSUE TITLE
Creation of the default folder layout for mesos-{slave, master} options

### ISSUE THREAD

**Issue by jroimartin** [danigiri/mesos-build-helper#1]
Creation of the default folder layout for mesos-{slave, master} options within the rpm.

More info: http://frankhinek.com/setup-mesos-multi-node-cluster-on-ubuntu/

We should check first if this default layout is standard or mesosphere-centric.

**Comment by danigiri** [comment]
Version 0.24.0 at feature branch loads and starts, which is a good thing but also expected, as `make install` does not create the folders in question.

**Comment by danigiri** [comment]
It seems that these configuration files are read by `mesos-init-wrapper`, which has an unclear license

**Comment by jroimartin** [comment]
Closing because I don't think this issue is relevant anymore. Even the link is gone.
